version: '3.8'

services:
  chatterbox-tts-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./voices:/app/voices
      - ./reference_audio:/app/reference_audio
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - hf_cache:/app/hf_cache
    restart: unless-stopped
    environment:
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia

volumes:
  hf_cache:
